version: "3.9"

services:
  backend:
    image: crpi-4r2gidb79yjyny4o.cn-hangzhou.personal.cr.aliyuncs.com/shawnyao/cugrs:latest
    container_name: cugrs-backend
    ports:
      - "5008:5008"
    environment:
      GEOVIEW_CONFIG: embedded
      DATABASE_BACKEND: sqlite
      SQLITE_DATABASE_PATH: /app/backend/static/geoview.sqlite3
      GEOVIEW_BACKEND_ENABLED: "true"
      GEOVIEW_FRONTEND_ENABLED: "false"
      GEOVIEW_MINER_SERVICE_ENABLED: "false"
      REQUIRE_GPU: ${REQUIRE_GPU:-true}
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES:-all}
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      HF_HOME: /root/.cache/huggingface
      HF_HUB_CACHE: /root/.cache/huggingface/hub
      TRANSFORMERS_OFFLINE: "1"
      HF_DATASETS_OFFLINE: "1"
      HF_HUB_OFFLINE: "1"
      TORCH_HOME: /root/.cache/torch
      PADDLE_HOME: /root/.paddle
      GEOVIEW_MODEL_ROOT: /app/backend/model
      GEOVIEW_EXTERNAL_STATIC_ROOT: /data/geoview/static
      GEOVIEW_INTERNAL_STATIC_ROOT: /app/backend/static
      GEOVIEW_ASSET_READ_ORDER: external,internal
    volumes:
      - /data/geoview:/data/geoview
      # HuggingFace & other models cache (persists across container restarts and supports offline deployment)
      - ./offline_cache/huggingface:/root/.cache/huggingface
      - ./offline_cache/torch:/root/.cache/torch
      - ./offline_cache/paddle:/root/.paddle
      - ./offline_cache/paddle:/root/.cache/paddle

    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
