nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

frontend:
  replicaCount: 1
  image:
    repository: crpi-4r2gidb79yjyny4o.cn-hangzhou.personal.cr.aliyuncs.com/shawnyao/geoview-frontend
    tag: 20260521-registration-preprocess2
    pullPolicy: IfNotPresent
  runtimeConfig:
    backendUrl: "http://172.20.20.240:31839/186/5008"
    backendProtocol: http
    backendHost: ""
    backendPort: ""
    backendAssetMode: sendfile
    frontendAssetDebug: false
    frontendDebug: false
    frontendVersionTag: "20260521-registration-preprocess2"
    minerEnabled: false
    minerUrl: ""
    baiduMapAccessKey: ""
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
  service:
    type: ClusterIP
    port: 3000
    targetPort: 80
    nodePort: null
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: geoview-frontend.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
  persistence:
    enabled: true
    existingClaim: ""
    mountPath: /data
    storageClassName: csi-block-sc2
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    annotations: {}
