frontend:
  image:
    repository: 172.20.20.107:8443/your-project/geoview-frontend
    tag: "20260521-registration-preprocess2"
    pullPolicy: IfNotPresent
  runtimeConfig:
    backendUrl: "http://172.20.20.240:31839/186/5008"
    backendProtocol: http
    backendHost: ""
    backendPort: ""
    backendAssetMode: sendfile
    frontendAssetDebug: false
    frontendDebug: false
    minerEnabled: false
    minerUrl: ""
    baiduMapAccessKey: ""
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
  service:
    type: ClusterIP
    port: 3000
    targetPort: 80
    nodePort: null
  persistence:
    enabled: true
    existingClaim: ""
    mountPath: /data
    storageClassName: csi-block-sc2
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    annotations: {}
