apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geoview.fullname" . }}-config
  labels:
    {{- include "geoview.labels" . | nindent 4 }}
data:
  config.yaml: |
    port:
      backend: {{ .Values.app.config.port.backend }}
      frontend: {{ .Values.app.config.port.frontend }}
    host:
      backend: {{ .Values.app.config.host.backend | quote }}
      frontend: {{ .Values.app.config.host.frontend | quote }}
    baidu_map:
      access_key: {{ .Values.app.config.baiduMapAccessKey | quote }}
    debug: {{ .Values.app.config.debug }}
    miner:
      enabled: {{ .Values.app.config.miner.enabled }}
      frontend_port: {{ .Values.app.config.miner.frontendPort }}
      backend_port: {{ .Values.app.config.miner.backendPort }}

