{{- if .Values.app.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "geoview.appName" . }}
  labels:
    {{- include "geoview.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
  {{- with .Values.app.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.app.ingress.className }}
  ingressClassName: {{ .Values.app.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.app.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "geoview.appName" $ }}
                port:
                  name: {{ .servicePort }}
          {{- end }}
    {{- end }}
{{- end }}

