{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoview.mysqlName" . }}
  labels:
    {{- include "geoview.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  clusterIP: None
  selector:
    {{- include "geoview.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
{{- end }}

