apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geoview.fullname" . }}-secret
  labels:
    {{- include "geoview.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-password: {{ ternary .Values.mysql.auth.password .Values.externalMySQL.password .Values.mysql.enabled | quote }}
  mysql-database: {{ ternary .Values.mysql.auth.database .Values.externalMySQL.database .Values.mysql.enabled | quote }}
  mysql-username: {{ ternary .Values.mysql.auth.username .Values.externalMySQL.username .Values.mysql.enabled | quote }}
  {{- if .Values.mysql.enabled }}
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | quote }}
  {{- end }}

